### PR TITLE
Swift3 - Created GMPDouble class with comparison protocols

### PR DESCRIPTION
**Pull request by twodayslate**
I left your `IntegerBig` stuff alone but I made `DoubleBig` into a `GMPDouble class`.  This allows for `deinit` to be defined as discussed in [my original pull request](https://github.com/NeoTeo/SwiftGMP/pull/1). I am open to a name change to just `Double` as Swift is automatically name-spaced by the module.

I also made `GMPDouble` conform to the `Equatable` and `Comparable` protocols. Lastly I added a description variable instead of calling the `toString()` function. 

The tests have also been updated to support these changes.

### CODE REVIEW

**Comment by NeoTeo** [comment]
Looks good. I do think we need to get a consistent naming worked out. 

I'm not particularly married to the IntegerBig name (pretty sure the naming was inspired by the osxgmp wrapper) but whatever name is chosen it needs to be the same for the various types. 

I'm not a fan of overloading Double and Int because it makes the code less clear to read, especially considering that there is no requirement to use the namespace prefix. Although you currently write SwiftGMP.GMPDouble you could just write GMPDouble and if it was renamed to Double you'd have trouble distinguishing a system Double from a GMP Double. Perhaps the GMP prefix on all types is clearest if not prettiest.

Also note that as of Swift 3 ([SE-0091](https://github.com/apple/swift-evolution/blob/master/proposals/0091-improving-operators-in-protocols.md)) you can define your custom operators inside the class as static func.

**Comment by twodayslate** [comment]
I was having a hard time to get the static functions to compile. That is what I originally tried to do. `GMPDouble` is good with me :)

**Comment by NeoTeo** [comment]
Ok, updated with GMPInteger. Beware you'll need to update your calls in your own projects. 
I'm using operators as static functions inside the class. Have a look to see if you can see why yours might not be working.

**Comment by twodayslate** [comment]
Yeah, the static functions do not work for me. 
screen shot 2016-08-27 at 17 47 47

Xcode Version 8.0 beta (8S128d). Editing: Going to update Xcode...

**Comment by NeoTeo** [comment]
Yeah, we're up to beta 6 (8S201h)

**Pull request merged**
