### PR TITLE
Swift3 - DoubleBig

### PR DESCRIPTION
**Pull request by twodayslate**
Features
- Now supports floating points!
- Init floating points with Double or String
- Add and subtract for floating points
- Get the String value for a floating point

I wanted something with floating points so I added that to this wrapper. I'd personally rather call it `BigDouble` but I left the original naming convention. I also put the `clear` function as part of the class. I'd be curious on your thoughts on that. Tests have also been included and broken up by type. 

I'll be adding more things as I progress. I'll be integrating this into a personal iOS project.

### CODE REVIEW

**Comment by NeoTeo** [comment]
@twodayslate Thanks! I'm on hols until next week when I will review.

**Comment by twodayslate** [comment]
Thoughts on converting the `struct` to a `class` so there can be a `deinit` function?

**Comment by NeoTeo** [comment]
Hi @twodayslate.
I still haven't time to give this my full attention but a quick test using your latest commit fails the Carthage xcodebuild call when building SwiftGMP as a dependency (in this case of SwiftBase58).

```
/usr/bin/xcrun xcodebuild -project /Users/teo/tmp/pulltest/SwiftBase58/Carthage/Checkouts/SwiftGMP/SwiftGMP.xcodeproj -scheme SwiftGMP -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build
Build settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO

=== CLEAN TARGET SwiftGMP OF PROJECT SwiftGMP WITH CONFIGURATION Release ===

Check dependencies
Swift is unavailable for i386 on macOS; please remove i386 from ARCHS (currently 'x86_64 i386')

** CLEAN FAILED **


The following build commands failed:
    Check dependencies
(1 failure)
=== BUILD TARGET SwiftGMP OF PROJECT SwiftGMP WITH CONFIGURATION Release ===

Check dependencies
Swift is unavailable for i386 on macOS; please remove i386 from ARCHS (currently 'x86_64 i386')

** BUILD FAILED **


The following build commands failed:
    Check dependencies
(1 failure)
```

**Comment by twodayslate** [comment]
That would have been my [latest commit](https://github.com/NeoTeo/SwiftGMP/pull/1/commits/8c195b4c97e88fc09bcd3274175c88651993e14e). I was having trouble integrating it into my iOS application. It was saying the architecture was wrong - hence me setting it to universal. [Still having some issues with the framework but that is probably my fault.](http://stackoverflow.com/questions/38987188/swift3-framework-module-is-empty)

[This commit](https://github.com/NeoTeo/SwiftGMP/pull/1/commits/50ff7c642fb952c8f8ab69ba8ff40aa0aac80c2f) should pass the tests and build correctly for macOS.

Sorry.

**Comment by NeoTeo** [comment]
No worries. As mentioned I'll give it a good look next week.

:) Teo

**Comment by twodayslate** [comment]
I think I figured out my problems a little bit. You need multiple projects to support multiple architectures. I'm not there yet but getting closer. 

https://github.com/twodayslate/SwiftGMP/tree/swift3universal

**Comment by NeoTeo** [comment]
@twodayslate No, it's been working fine for multiple architectures.

**Comment by twodayslate** [comment]
Then I must be doing something terribly wrong. I'll revert my arch change then the Pr should be good to go for when you have time to review it.

edit:// reset complete.
edit2:// Just got it working in my iOS project. Just dragging and dropping the .framework file didn't work for me. I had to drag the project file, then add the library path in my build settings. :\

**Comment by NeoTeo** [comment]
@twodayslate  Looks good to me after the reset. Thank you very much for your contribution :) 
Going forward I'd like to
1) Separate the int and double into separate files (I'll do that soon)
2) Move away from tests that rely on visual inspection (I know, I started it :) )

Thanks again.

**Comment by twodayslate** [comment]
I can work on this as well some more. What do you think about making the `stuct`s into `class`es so we can free/clear the values in the `deinit`? I also have no idea why I am having [this problem](http://stackoverflow.com/questions/38987188/swift3-framework-module-is-empty).

**Comment by NeoTeo** [comment]
I'm not averse to classes when necessary. What is currently not being deinited that would require a class deinit?
I replied with a suggestion to your question [on SO](http://stackoverflow.com/questions/38987188/swift3-framework-module-is-empty/39148300#39148300), hope it's useful.

**Comment by twodayslate** [comment]
To free the `mpf_t` and `mpz_t` instances. https://gmplib.org/manual/Memory-Management.html#Memory-Management

**Comment by NeoTeo** [comment]
Ah, yes. C libraries. I'll get that sorted.

**Pull request merged**
